### ISSUE TITLE
RTT capsule needs example console usage

### ISSUE THREAD

**Issue by JayKickliter** [tock/tock#1022]
I missed the chance make to make this comment on PR #1013. RTT is something I plan to use on my board. The capsule documentation shows how an RTT instance and it's required alarm, but now how to use it as a console. Specifically, I'd like to replace a UART-backed console with one backed by RTT. Additional documentation would be helpful.

**Comment by bradjc** [comment]
In the meantime it looks like this: https://github.com/tock/tock/blob/acd52832/boards/acd52832/src/main.rs#L263
