### ISSUE TITLE
u64 support for tock-regs?

### ISSUE THREAD

**Issue by andre-richter** [tock/tock#1087]
Hi,

short question: Would you be open to add u64 support to tock-regs or should I work with a fork if I want that?

AFAICS, I cannot implement the `IntLike` for u64 if I pull in tock-regs as an extern crate, because both the trait and the type I want to implement it for (u64) are foreign in that case.

Thanks,
Andre

**Comment by ppannuto** [comment]
I think we'd be thrilled with `u64` support. We have `u8`, `u16`, and `u32`, we just happen to work on 32-bit microcontrollers, so that's where we stopped :)
