### ISSUE TITLE
Push 2018 edition of tock-registers

### ISSUE THREAD

**Issue by andre-richter** [tock/tock#1253]
@bradjc @ppannuto I see you already updated tock-registers to the 2018 edition. Could you push a respective new version to crates.io so that this change is reflected there as well?

This allows me to bump https://crates.io/crates/register to the 2018 edition :)

Thanks a lot,
Andre

**Comment by ppannuto** [comment]
Sure thing. I'll push to crates.io once #1254 is merged.

**Comment by ppannuto** [comment]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/339422/50174410-fd5ff480-02ae-11e9-9517-d2b64d05f00f.png">
And we're live :)
