### ISSUE TITLE
Building docs should find all boards automatically

### ISSUE THREAD

**Issue by ppannuto** [tock/tock#1256]
Currently, `tools/build-all-docs.sh` manually enumerates boards, which means we have to remember to add them. It'd be better to use `tools/list_boards.sh`, but this needs just a touch of integration work, since the doc-building currently relies on (arbitrarily) building one board completely first to pick up the rest of the kernel, so the list needs to filter out whatever board it start with.

**Comment by mwilbur** [comment]
I have something for this.  I just need to wait until I'm home to do a pull request as my work blocks port 22 to github.com (don't ask).

**Comment by bradjc** [comment]
Merged!
