### ISSUE TITLE
Support other STM32F4xx, maybe STM32F1xx

### ISSUE THREAD

**Issue by sh7dm** [tock/tock#1271]
I've got STM32F4xx and STM32F1xx based boards, but all of their uCs aren't in support list. Could you please add support for them?

**Comment by bradjc** [comment]
#1674

**Comment by bradjc** [comment]
Closing due to age. We are happy to see STM32 support grow, and will merge new STM32-based boards as long as they meet the [minimum requirements](https://github.com/tock/tock/blob/master/doc/Porting.md#adding-a-platform-to-tock-repository).
