### ISSUE TITLE
Provide a way to specify MPU access permissions

### ISSUE THREAD

**Issue by rajivr** [tock/tock#1280]
ARM architecture allows for different memory types (normal/device memory), shareability and accessibility domains. 

When configuring a region, it is possible to tell the MPU access attributes. Currently for Cortex-{M3, M4} we default to _Strongly Ordered, Shareable_, which might not be appropriate for all MCUs.

Details for MPU access attributes can be found in Section 4.5.6 and 4.5.9 of [Cortex M4 Devices Generic User Guide](http://infocenter.arm.com/help/topic/com.arm.doc.dui0553b/DUI0553.pdf)

In the MPU trait, we might want to provide a way to specify memory attributes when allocating and updating memory regions.

**Comment by bradjc** [comment]
Closing due to age. If anyone wants to revisit this please re-open or add a comment or start a new issue!
