### ISSUE TITLE
Replace `mem::uninitialized` with `MaybeUninit`

### ISSUE THREAD

**Issue by niklasad1** [tock/tock#1320]
`mem::uninitialized` has been deprecated in favor of MaybeUninit in `Rust 1.36`, for more info why see https://gankro.github.io/blah/initialize-me-maybe/#memuninitialized

I can only find [this](https://github.com/tock/tock/blob/master/libraries/tock-cells/src/map_cell.rs#L79) use of it

However, we should bump `rustc` to 1.36 and remove all occurrences of `mem::uninitialized`

**Comment by estk** [comment]
I'd like to work on this one. I'll have some time on the weekend to work on it.

**Comment by niklasad1** [comment]
Closed by #1331
