### ISSUE TITLE
Improve context switch performance by reducing unnecessary state save

### ISSUE THREAD

**Issue by garasubo** [tock/tock#1433]
Please correct me if I'm wrong.
The ISR handler saves registers when the interrupt comes from user mode (unprivileged thread mode). However, this storing is done in switch_to_user function (https://github.com/tock/tock/blob/9e6b2f622da27a3f8324e228761e426ca1e1bb28/arch/cortex-m4/src/lib.rs#L173). So, as long as switch_to_user function is the only path to enter user mode, this register storing seems unnecessary. And other handler don't have this storing logic as well (e.g. systick handler: https://github.com/tock/tock/blob/9e6b2f622da27a3f8324e228761e426ca1e1bb28/arch/cortex-m4/src/lib.rs#L36).

PR: #1432

**Comment by bradjc** [comment]
I think we sorted this out and improved it in #1432.
