### ISSUE TITLE
Tracking: Add Scheduler Options

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1441]
Right now Tock uses a priority scheduler, where the priority is set by the order of apps in the Process array. This would add at least one other option, and make it easier to add new schedulers.

- [x] Add a Scheduler trait.
- [x] Add round robin scheduler.

**Comment by alevy** [comment]
I believe @Ngalstyan4 is working on this

**Comment by hudson-ayers** [comment]
Is @Ngalstyan4 still working on this? I was considering taking a stab it

**Comment by bradjc** [comment]
Link to some ideas on this topic: https://docs.google.com/document/d/1nCJkTyY0h-ZRjyoW90uSSkLqQ541FZmUh0atiGk3tVk/edit

**Comment by bradjc** [comment]
#1767

**Comment by bradjc** [comment]
#1767 has been merged!
