### ISSUE TITLE
Kernel panics when the debug buffer is full

### ISSUE THREAD

**Issue by gendx** [tock/tock#1442]
Kernel debugging uses a circular buffer to store messages until they are sinked to a suitable output (UART, RTT, etc.). However, if this buffer gets full, the kernel immediately panics:

https://github.com/tock/tock/blob/95c1dc9d2665d4570afa26ab6935b0ade7fb88da/kernel/src/debug.rs#L485-L495

This is quite annoying when debugging protocols such as USB, where a lot of events happen quite frequently. This can be somewhat mitigated with a larger buffer (https://github.com/tock/tock/issues/1373) but this is still unreliable (e.g. sometimes the debug sink has a random delay and the kernel fills the buffer in the meantime).

Is there any reason for the kernel to panic when the circular buffer is full? I think that the debug messages should be dropped instead (possibly with a marker message such as `\n*** debug buffer full ***\n`), until the buffer gets flushed again.

**Comment by ppannuto** [comment]
As the person who wrote that behavior: short answer, no.

The debug stuff is fairly old, and in the early days it seemed better to not discard data, especially when even the debug/uart stuff was fragile. That's less true today, and I'd be supportive of a `buffer full` message change.
