### ISSUE TITLE
New Tock register release to crates.io

### ISSUE THREAD

**Issue by andre-richter** [tock/tock#1444]
Hi @ppannuto et al.,

Kindly request you to craft a new release of tock registers containing #1410, so I can pick it up for our registers-rs crate and incorporate it into our OS tutorials.

Thanks,
Andre

**Comment by andre-richter** [comment]
Upload to crates.io pending? 

Sorry to be annoying :grin:

**Comment by ppannuto** [comment]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/339422/68432222-daf5f480-0168-11ea-9c41-406c32ba31f3.png">

And it's live! :)

**Comment by andre-richter** [comment]
:heart:
