### ISSUE TITLE
macro static_init!

### ISSUE THREAD

**Issue by bandheight** [tock/tock#1470]
The current implementation of this macro is
```rust
macro_rules! static_init {
    ($T:ty, $e:expr) => {
        {
            use core::{mem, ptr};
            static mut BUF: Option<$T> = None;
            let tmp : &'static mut $T = mem::transmute(&mut BUF);
            ptr::write(tmp as *mut $T, $e);
            tmp
        };
    }
}
```
and why not is
```rust
macro_rules! static_init {
    ($T:ty, $e:expr) => {
        {
            use core::mem;
            mem::transmute::<&mut $T, &'static mut $T>(&mut $e)
        };
    }
}
```
?

**Comment by gendx** [comment]
See also https://github.com/tock/tock/pull/1446 and https://github.com/tock/tock/issues/1447 for related discussions about `static_init`.

**Comment by bandheight** [comment]
@gendx I look at this discussions. You are right! Use **MaybeUninit** to define a mutable static variable and then init later finally get mut ref is elegant way.

However, I test my way, I found this way is more memory efficient than you and origin way.
So, is there any other side effect of directly extending the lifetime by **mem::transmute** .

**Comment by niklasad1** [comment]
@bandheight in your example it seems possible to pass for example an array on the stack instead of `static mut` and transmuting it as `&'static mut T` is undefined behavior.

**Comment by bandheight** [comment]
The return value of `$e` is actually stored on the stack. You are right.

**Comment by bandheight** [comment]
If we do this?
```rust
macro_rules! static_init {
    ($T:ty, $e:expr) => {
        {
            use core::mem;

            unsafe fn extend_lifetime(mut r: $T) -> &'static mut $T {
                mem::transmute::<&mut $T, &'static mut $T>(&mut r)
            }

            extend_lifetime($e)
        };
    }
}
```

**Comment by alevy** [comment]
@bandheight I believe that still stores the value on the stack, and simply “lies” about the value’s lifetime.

**Comment by gendx** [comment]
Taking a reference to a temporary expression and extending its lifetime is definitely undefined behavior that will break your program, and is precisely a memory safety issue that Rust's lifetimes aim to protect against. This is `unsafe` for a good reason.

**Comment by bandheight** [comment]
There is a description of `core::mem::transmute` in the documentation.

> Extending a lifetime, or shortening an invariant lifetime. This is advanced, very unsafe Rust!

Maybe we really shouldn’t do it in such a `unsafe` way.
