### ISSUE TITLE
Synchronous callback bug in transmit_buffer of virtual_uart

### ISSUE THREAD

**Issue by phil-levis-google** [tock/tock#1496]
https://github.com/tock/tock/blob/ad676eef883ae74d4a19f6b6313ad98534bd6c09/capsules/src/virtual_uart.rs#L353

calls `do_op` when there is a transmission request. If there are no pending requests, it can be handled immediately. If it fails, it issues a `transmitted_done` callback with the error:

https://github.com/tock/tock/blob/ba11fd96bbdb8edcc3f202382b8d275f0b36375f/capsules/src/virtual_uart.rs#L190

We've agreed that callbacks should not occur during calls, for race condition/data integrity reasons. If a transmit call to a virtualized UART is handled immediately but fails, the callback will be issued synchronously. This should instead use a deferred call to issue the callback asynchronously.

**Comment by hudson-ayers** [comment]
Fixed by #1522
