### ISSUE TITLE
Restarting Apps no longer works

### ISSUE THREAD

**Issue by hudson-ayers** [tock/tock#1524]
Using the debug_process_restart capsule to restart apps no longer works. After the app restarts, it immediately panics again. This was tested using the `blink` app in libtoock-c, as well as several other apps.

I did a (manual) git bisect, and found that this functionality broke after PR #1318 was merged, which introduced a new `UserspaceKernelBoundary`. 

In case this is useful, I tried inserting a manual `panic!()` on the seconds app hard fault (after the intentional restart) and the debug output is as follows:

```
---| Fault Status |---
Memory Management Unstacking Fault: true
Forced Hard Fault:                  true
Fault Status Register (CFSR):       0x00000008
Hard Fault Status Register (HFSR):  0x40000000

---| App Status |---
App: blink   -   [Fault]
 Events Queued: 0   Syscall Count: 0   Dropped Callback Count: 0
 Restart Count: 0
 Last Syscall: None

 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x2000A000═╪══════════════════════════════════════════╝
             │ ▼ Grant         816 |    816          
  0x20009CD0 ┼───────────────────────────────────────────
             │ Unused
  0x20008C00 ┼───────────────────────────────────────────
             │ ▲ Heap       536906752 | 536911056               S
  0x00000000 ┼─────────────────────────────────────────── R
             │ Data              0 |      0               A
  0x00000000 ┼─────────────────────────────────────────── M
             │ ▼ Stack           0 | 3758063616          
  0x00000000 ┼───────────────────────────────────────────
             │ Unused
  0x20008000 ┴───────────────────────────────────────────
             .....
  0x00040800 ┬─────────────────────────────────────────── F
             │ App Flash      2004                        L
  0x0004002C ┼─────────────────────────────────────────── A
             │ Protected        44                        S
  0x00040000 ┴─────────────────────────────────────────── H

  R0 : 0x0004002C    R6 : 0x20008898
  R1 : 0x20008000    R7 : 0x20008000
  R2 : 0x00002000    R8 : 0x00000000
  R3 : 0x20008C00    R10: 0x00000000
  R4 : 0x0000000A    R11: 0x00000000
  R5 : 0x0000000A    R12: 0xF15B4CF2
  R9 : 0x20008800 (Static Base Register)
  SP : 0x20008C00 (Process Stack Pointer)
  LR : 0x00040347
  PC : 0x00040055
 YPC : 0x00040346

 APSR: N 0 Z 1 C 1 V 0 Q 0
       GE 0 0 0 0
 EPSR: ICI.IT 0x00
       ThumbBit true 
To debug, run `make debug RAM_START=0x20008000 FLASH_INIT=0x40055`
in the app's folder and open the .lst file.
```

I also attempted to backtrace the second fault using gdb, and it shows the fault as originating in the `switch_to_user()` function in `arch/cortex-m4/src/lib.rs`. I think that just means that the fault occurs within the application code though, and am not sure how to trace into the actual application fault using gdb.

Reading the discussion on #1318 between @bradjc and @ppannuto it wasn't totally clear to me whether the new interface was actually intended to support restarting, so perhaps this is not a bug after all, but an intentional decision until the interface is further updated?

**Comment by bradjc** [comment]
Thanks for noticing this and starting to debug. The cause seems to be changes to process.rs and how apps are created that were not reflected in the restart code. #1529 updates the restart code to fix this.
