### ISSUE TITLE
Broken GPIOs on nRF52840-DK

### ISSUE THREAD

**Issue by gendx** [tock/tock#1557]
I flashed the latest Tock kernel on a nRF52840-DK board, along with the `button_leds` example app (https://github.com/tock/libtock-rs/blob/c84685a99ea55cdb36823c234d4d1fc00dbc3672/examples/button_leds.rs).

The app is supposed to toggle a LED whenever the corresponding button is pressed, but with the latest Tock kernel it's not working as intended anymore. Most button presses seem just ignored by Tock (i.e. the LED is not toggled).

**Edit 1:** I added some debugging and it seems that no GPIO interrupt is delivered at the [`InterruptService` level](https://github.com/tock/tock/blob/master/chips/nrf52840/src/interrupt_service.rs) - unless when the LED then actually toggles.

**Edit 2:** Buttons 3 and 4 sometimes work, buttons 1 and 2 seem to never work. But I can also "trigger" the buttons 1 and 2 by touching some metallic parts of the board with my finger (instead of the buttons themselves).

**Edit 3:** Potential causes:
- https://github.com/tock/tock/pull/1504
- https://github.com/tock/tock/pull/1503
- https://github.com/tock/tock/pull/1541

**Comment by gendx** [comment]
**Update:** The problem is that setting the `PullUp` floating state was removed in #1541 - and that the component doesn't support setting that. CC @hudson-ayers @bradjc.

- https://github.com/tock/tock/pull/1541/files#diff-29f6b060c97fc794cb5569c7c1a95f45L233-L235
- https://github.com/tock/tock/pull/1541/files#diff-444e1e15bd50663750639738ff8576a1L287-L289

Currently working on a fix.

**Comment by gendx** [comment]
Also I think that we should be doing a better job at testing (and documenting more precisely which tests have been run) before merging these kind of breaking changes to boards. The relatively simple `button_leds` test on the migrated boards in https://github.com/tock/tock/pull/1541 should have caught it.

**Comment by hudson-ayers** [comment]
Thanks for catching this, sorry that I introduced the bug in the first place. I checked functionality on Hail and Imix and got lazy on testing..didn't realize that the nrf52 boards had to set the floating state for the buttons while the sam4l boards do not.
