### ISSUE TITLE
Support deploying kernels via OpenOCD

### ISSUE THREAD

**Issue by jrvanwhy** [tock/tock#1626]
I'd like to deploy a kernel to the nrf52840-DK using OpenOCD rather than Segger's JLink tools. `tockloader` supports using OpenOCD already, but the Makefiles under `boards/` don't give us a way to pass the flags through to `tockloader`.

We should allow users of the `board/` Makefiles to program using OpenOCD.

**Comment by jrvanwhy** [comment]
I *think* this can be accomplished in a rudimentary manner for most of the boards by changing `TOCKLOADER_JTAG_FLAGS =` to `TOCKLOADER_JTAG_FLAGS ?=` in the Makefiles.

Would anyone object to a PR that makes that change?

**Comment by ppannuto** [comment]
I'm happy with a change to the conditional

**Comment by bradjc** [comment]
We could add a `make flash-openocd` target (or some other name).

**Comment by jrvanwhy** [comment]
Due to COVID-19, I am currently working remotely, and do not expect to return for a minimum of 3 weeks (probably much longer). I cannot work on this until I return to my desk, as that is where the dev hardware is.

**Comment by jrvanwhy** [comment]
To be clear, I intend to do this eventually, but either someone else needs to do the work or it is shelved for now.
