### ISSUE TITLE
Question on DMAChannel::enable

### ISSUE THREAD

**Issue by fpoli** [tock/tock#1634]
Hi! While looking for usages of unsafe code in the Rust ecosystem, I randomly stumbled upon this line

https://github.com/tock/tock/blob/4268a351d40bf55d9507efdee78cec5be22df26e/chips/sam4l/src/dma.rs#L234

Could you help me understanding the logic here? In particular
1. Shouldn't the test be `num_enabled == 0`, to identify the first time that `DMAChannel` is enabled? `atomic_xadd` returns the value before the increment, so `num_enabled == 1` is true the _second_ time `DMAChannel` is enabled.
2. Why are `HSBClock` and `PBBClock` enabled anyway at the beginning of the `enable` method, independently from the `num_enabled` test? It seems a workaround for the problem above.

(It's the first time that I look at Tock, so it's possible that I'm missing some context.)

**Comment by fpoli** [comment]
Also, if the `DMAChannel` is meant to be used by multiple threads I think that by concurrently calling `enable` and `disable` it's possible to reach a state where `self.enabled` is false but `num_enabled` is greater than zero.

**Comment by phil-levis** [comment]
Good question! This code is 5 years old, written by Amit. I've assigned it to him.

**Comment by alevy** [comment]
@fpoli this seems like a bug to me.

Could be worth both switching the intrinsic out for the stable version in `core::atomic` as well as fixing the bug and testing it.

Thanks for finding this!
