### ISSUE TITLE
[RFC] PanicButton capsule/component

### ISSUE THREAD

**Issue by gendx** [tock/tock#1640]
While debugging https://github.com/tock/tock/issues/1629, I found it useful to be able to trigger a kernel panic when pressing a given button.

This is specially useful when the debug output itself is stalled (due to scheduling bugs), because the panic output uses a "more direct" writing mechanism (no alarms/callbacks involved), as defined in `boards/foo/src/io.rs`.

## Proposal

Such a component would be rather simple to build on top of the current GPIO HIL.

1. A `PanicButton` capsule. This would allow to create a new panic button with a GPIO pin, mode and floating state. It would implement the `gpio::ClientWithValue` HIL, with the `fire` function containing a `panic` statement. This wouldn't be linked to any userspace driver, so I'm not sure whether a capsule is even the right place to do this. Some code could be shared with `Button`, e.g. `ButtonState` to trigger a panic only when the button is `Pressed`, so the code could be in the same file (`capsule/src/button.rs`).
1. The corresponding component. Somewhat similar to the button component. But I assume that a single GPIO would be sufficient for debugging purposes, rather than an array as the current button component has.
1. By default, no board would be connected to such component, but thanks to the component it should be rather easy to set it up when needed (i.e. one statement in the board file).

What do you think?

**Comment by bradjc** [comment]
Sounds great.

We should probably aggregate a list of these types of tools somewhere:
- https://github.com/tock/tock/blob/master/capsules/src/debug_process_restart.rs
- the crash_dummy libtock-c app
- the `fault` command in the process console
