### ISSUE TITLE
OpenTitan: Unable to write large strings more than once after boot

### ISSUE THREAD

**Issue by alistair23** [tock/tock#1787]
After turning on the OpenTitan FPGA board I can boot Tock with the `examples/tests/printf_long` app and see the long string be printed.

If I flash the app again the print does not occur. It won't happen again until I power cycle the board and then re-load the app.

Not all printing is broken though, as I still see the `OpenTitan initialisation complete. Entering main loop` print and if I load two apps (with the long print being just 1 of the apps) I see the other app print.

**Comment by bradjc** [comment]
Should we try to fix this for 1.5?

**Comment by alistair23** [comment]
I don't think so.

**Comment by alistair23** [comment]
Seems to be fixed, closing this.
