### ISSUE TITLE
Is it possible tockloader supports STM32 board?

### ISSUE THREAD

**Issue by dpinthinker** [tock/tock#1848]
Just found that tockloader doesn't support STM32 board. Does anyone know the reason? Is it possible tockloader supports STM32 board?

```
➜  nucleo_f446re git:(master) tockloader list-known-boards
Known boards: hail, imix, nrf51dk, nrf52dk, launchxl-cc26x2r1, ek-tm4c1294xl
```

**Comment by bradjc** [comment]
Adding known boards pretty much boils down to adding entries to this dict: https://github.com/tock/tockloader/blob/master/tockloader/board_interface.py#L19. Tockloader uses openocd, it's just a matter of making sure tockloader is calling it with the correct options and flags.

**Comment by dpinthinker** [comment]
Great! I will try to add one.
Thanks!
