### ISSUE TITLE
Fix favicon for rustdoc generated docs

### ISSUE THREAD

**Issue by ppannuto** [tock/tock#1864]
Resurrecting the second bullet from #1334 

- [ ] Figure out how to fix favicon / logo more generally (here's a start https://github.com/tock/tock/tree/doc-updates)

**Comment by JOE1994** [comment]
The second link (https://github.com/tock/tock/tree/doc-updates) gives a 404 error 🦀

**Comment by ppannuto** [comment]
Hm.., looks like that branch has been deleted from github and isn't on my laptop :(

However, I remember that pointer to some ugly hack, and it looks like the tooling may have improved that an ugly hack is no longer necessary:
https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#html_favicon_url

While we're there, it'd be nice to update the `html_logo_url` as well.
