### ISSUE TITLE
Debugging over USB serial

### ISSUE THREAD

**Issue by brghena** [tock/tock#1972]
For platforms with only USB virtual consoles, we need to support debugging over that interface.

On a panic, we traditionally use the synchronous UART to print debugging information. However, this synchronous method seems very hard to impossible to implement for USB CDC. Crashes in applications should still be debuggable since the kernel is trustworthy, but would require some changes in the kernel for how they are handled. Crashes in the kernel are a harder question.

**Comment by ppannuto** [comment]
I don't think the goal of the panic / emergency path is usually to be terribly efficient. While I certainly don't have the whole state machine in my head, couldn't the synchronous write just start the write event for a byte, then spin on `EVENTS_ENDEPOUT[X]` until the byte is sent?

**Comment by hudson-ayers** [comment]
I am going to take a stab at this. If synchronous USB CDC output looks too difficult, I am going to try using the log functionality to log panic dump info to flash, and have the board print any existing panic dump at boot, such that any panics which occur after initialization can at least be debugged by just resetting the board.
