### ISSUE TITLE
Allow SysTick trait to be configured from boards crate

### ISSUE THREAD

**Issue by rajivr** [tock/tock#1998]
As mentioned [here](https://github.com/tock/tock/pull/1990#issuecomment-652218550), with SysTick trait is there seems to an assumption on being able to accurately get remaining time-slice in micro-seconds (in `get_remaining_us`). The way SysTick reference clock (STCLK) gets configured can vary depending on the tune-able parameters that chip vendor provides. Currently SysTick is initialized in `chip.rs` in the chip crate.

Clocks are usually setup in the board crate. We might have to consider some way allowing SysTick calibration to be done from board crate.

**Comment by hudson-ayers** [comment]
Whatever mechanism is ultimately used to address this should also be used for the watchdog.
