### ISSUE TITLE
Bootloader feature set

### ISSUE THREAD

**Issue by alevy** [tock/tock#205]
Proposed feature-set:

  * Shares code with kernel

  * Can replace kernel from binary over UART

  * Can replace processes from binaries over UART

  * Reports information about platform over UART

**Comment by bradjc** [comment]
- Negotiate a faster baud rate or somehow an adaptable baud rate.

**Comment by bradjc** [comment]
These exist or are in the works. If needed this could be moved to the `tock-bootloader` repository.
