### ISSUE TITLE
Does this support sipeed-lognan nano RISC-V

### ISSUE THREAD

**Issue by VedantParanjape** [tock/tock#2078]
Can this run on sipeed lognan nano RISC-V Board?

What are the minimum specs required for the chip to run this OS ?

**Comment by ppannuto** [comment]
The list of supported board is available here: https://github.com/tock/tock/tree/master/boards#platforms-supported-by-tock

The [Porting Guide](https://github.com/tock/tock/blob/master/doc/Porting.md) covers the minimum requirements and what's required to get a new platform up and running.

**Comment by VedantParanjape** [comment]
Thanks, this helped.
