### ISSUE TITLE
USB: Need functions to reset data toggle in UsbController trait

### ISSUE THREAD

**Issue by namyoonw** [tock/tock#2096]
USB data Packet ID (PID) toggle should be reset at the device side by host request in these cases:
- Standard Device Request, SetConfiguration => the data PID should be zero for all endpoints.
- Standard Endpoint Request, ClearFeature => the data PID should be zero for the specified endpoint (both in and out).

Without this, possibly it may happen that the device never gets a packet from the host because it is dropped for data PID mismatch reason, and the host hangs.

The proposed change is
- UsbController trait defines these functions:
   -  fn set_config(&self, _conf_val: usize);
      // usb device driver resets data PID for all endpoint.
   -  fn endpoint_reset(&self, endpoint: usize);
      // usb device driver resets data PID for the given endpoint.
- ctrl_setup() of capsules::usb::usbc_client_ctrl::ClientCtrl handles these requests:
  - handle_standard_device_request() should call self.controller.set_config() on StandardRequest::SetConfiguration.
  - Add handle_standard_endpoint_request(), and let it call self.controller.endpoint_reset() on StandardRequest::ClearFeature.

**Comment by bradjc** [comment]
I'm not sure I understand what the data toggle is. Is that a USB parameter?

**Comment by namyoonw** [comment]
I meant a binary data packet ID (PID) in the low level. One party (host or dev) sends a packet with a PID, and sends next packet with PID toggled.

https://www.beyondlogic.org/usbnutshell/usb4.shtml

Sometimes, a sender and a receiver might not agree each other on a PID because of some accidental factors either physically (by power status change or connection change) or logically (by false firmware logic).

**Comment by bradjc** [comment]
Moved to #1940
