### ISSUE TITLE
CI-Job: Rustdoc Documentation not enforced on GitHub?

### ISSUE THREAD

**Issue by gendx** [tock/tock#2124]
I just ran `make ci-nosetup` and this triggered the following error:

```rust
********************************************************************************
* CI-Job: Rustdoc Documentation                                                *
********************************************************************************

...
Documenting nano33ble
make[3]: Entering directory '/tock/boards/nano33ble'
...
error: unused attribute
 --> boards/nano33ble/src/main.rs:6:1
  |
6 | #![no_main]
  | ^^^^^^^^^^^
  |
  = note: `-D unused-attributes` implied by `-D warnings`
```

**Comment by ppannuto** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/339422/94287544-4e346080-ff0b-11ea-9416-09745d26224a.png">

Looks like 
```
boards/Makefile.common: $(Q)RUSTDOCFLAGS='-Z unstable-options --document-hidden-items -D warnings' $(CARGO) --color=always doc $(VERBOSE) --release --package $(PLATFORM) --target-dir=$(TARGET_DIRECTORY) 2>&1 | tee /dev/tty | grep -q warning && (echo "Warnings detected during doc build" && if [[ $$CI == "true" ]]; then echo "Erroring due to CI context" && exit 33; fi) || if [ $$? -eq 33 ]; then exit 1; fi
```

isn't working like it should..

**Comment by hudson-ayers** [comment]
that looks like our classic "works in bash, but not in the default ubuntu shell (dash)" problem.

**Comment by alistair23** [comment]
Can we force the CI to use Bash?

**Comment by hudson-ayers** [comment]
> Can we force the CI to use Bash?

We actually do do this in the main Makefile (`SHELL := bash` is line 13 of the Makefile), but not in `boards/Makefile.common`, so perhaps we should apply it there as well. Unfortunately it seems that the Makefile calling a shell script in tools which then calls make again is enough to run some code with the system shell unless every Makefile specifies the shell as bash

**Comment by alistair23** [comment]
Could we run this as part of the CI setup?
```shell
rm /bin/sh
ln -s /bin/sh /bin/bash
```

**Comment by hudson-ayers** [comment]
Probably, but we would have to carefully gate it such that it only actually is executed as part of a github action -- I can imagine developers being upset if we changed their default shell on them when they were just trying to test the Tock CI on a PR. Also, who knows if any other ubuntu-specific aspects of the actions workflow depend on the default shell being dash (unlikely, but possible..?)

Changing the default shell in Makefile.common works (just tested) so I would probably prefer that
