### ISSUE TITLE
tock-registers: Next release to crates.io?

### ISSUE THREAD

**Issue by andre-richter** [tock/tock#2138]
Hi all, @ppannuto,

I see that tock-registers got a fair share of changes since the 0.5.0 release. Especially the switch to `UnsafeCell` looks important.

Can you we make a new release to crates.io, or are there any gating issues?

Thanks,
Andre

**Comment by ppannuto** [comment]
No gating issues.. just hasn't hit the top of the priority queue here :/

We're very near a feature freeze for Tock 1.6 release. The release testing should more thoroughly cover all of the register changes -- not that we've seen any problems yet. Let's take advantage of that, and I'll plan on kicking out a tock-registers release contemporaneously with Tock 1.6 [likely timeline >1 week, <1 month].

**Comment by hudson-ayers** [comment]
@ppannuto gentle reminder about this
