### ISSUE TITLE
Add explicit list of valid error codes for `send_buffer` in USB HID HIL

### ISSUE THREAD

**Issue by ppannuto** [tock/tock#2139]
> The error codes for send_buffer are not documented. I assume the only error case is EBUSY if a buffer was already passed down the HIL - similarly to receive_buffer?

Pulling this out from the comment on #2130, it'd be good to get this in as well for completeness.

**Comment by alistair23** [comment]
Done! I added some documentation to https://github.com/tock/tock/pull/2094
