### ISSUE TITLE
OpenTitan: Alarm times are incorrect and stop running

### ISSUE THREAD

**Issue by alistair23** [tock/tock#2155]
When running the `blink` app on OpenTitan I can see two problems related to the alarm:
 1. The alarm times are incorrect. It seems that the alarms take roughly 5 times too long to occur.
 1. Eventually the alarms will stop occurring and the LEDs will stop flashing.

**Comment by lschuermann** [comment]
I guess this might be the same issue as #2143, which I'm happy to fix.

**Comment by hudson-ayers** [comment]
Closed by #2164
