### ISSUE TITLE
STM32F3DISCOVERY debug! Macro and Process Console Don't Work

### ISSUE THREAD

**Issue by kevtan** [tock/tock#2260]
Was wondering if anyone else was having issues with the UART1 connection for the STM32F3DISCOVERY board? For me, I am unable to get any sort of debugging output from the board. At first, I thought it had something to do with the SB10 solder bridge as described [here](https://docs.rust-embedded.org/discovery/06-hello-world/index.html) but even after shorting SWO and PB3, I'm still unable to establish a working serial connection.

**Comment by alexandruradovici** [comment]
There is a bug that is preventing stm32f3discovery from working, most probably due to this https://github.com/tock/tock/pull/2188. Increasing the stack size did not help for this boards.

**Comment by kevtan** [comment]
That PR does not seem the `stm32f303xc` or `stm32f3discovery` modules so I don't see how it could affect the operation for the STM32F3DISCOVERY board unless I'm missing something—did you mean to reference a different PR?

**Comment by krady21** [comment]
It was probably this one #2187.

**Comment by hudson-ayers** [comment]
Yeah, that was my PR, but I don't have stm32f3 hardware to test what broke, so any debugging help is appreciated.

**Comment by hudson-ayers** [comment]
This board passed the release testing for Tock 2.0, so this was fixed at some point (probably byhttps://github.com/tock/tock/pull/2784)
