### ISSUE TITLE
TicKV Hash Algorithm

### ISSUE THREAD

**Issue by alistair23** [tock/tock#2413]
TicKV has made some progress and is now at the point where we need a hash algorithm. The question now is which algorithm and which implementation.

The algorithm is not used for cryptography, so we don't need a crypto one.

Properties:
 * Fast
 * Easy-ish to implement on embedded systems
 * Good for kv stores and resistant to collisions
 * Produces a 64-bit hash

I have no intentions of inventing another algorithm. My plan was to use an existing one and probably also an existing implementation, unless there is a good reason to re-implement it (there rarely is).

I have found two main contenders, although I'm option to other options.

The main options I have found are:
 - [SipHasher](https://github.com/veorq/SipHash/blob/master/README.md): Provided but deprecated by [Rust core](https://doc.rust-lang.org/core/hash/struct.SipHasher.html) and now a [standalone crate](https://github.com/jedisct1/rust-siphash)
 - [FNV](https://www.isthe.com/chongo/tech/comp/fnv/index.html) has a [Rust crate](https://github.com/servo/rust-fnv)
 - ~~[SwissTable](https://abseil.io/blog/20180927-swisstables) used by Rust for it's [HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html)~~

Other options:
 - [Spooky hash](https://burtleburtle.net/bob/hash/spooky.html)

**Comment by alistair23** [comment]
@phil-levis thoughts?

**Comment by jrvanwhy** [comment]
SwissTable is a hash table, not a hash function.

You should probably consider Fnv as well.

**Comment by alistair23** [comment]
Thanks! I skimmed through the SwissTable section too quickly.

**Comment by alistair23** [comment]
At a quick look FNV opens up the possibility of a DOS from malicious apps with large keys. For smaller operations it does seem to be faster.

**Comment by l162** [comment]
Likely unrelated, but would it be possible to use set approximation (like a bloom filter) here? Have a `needs_alloc` (const generic) version of [Xor Filters](https://arxiv.org/abs/1912.08258) sitting around at home. Fuse filters may be particularly good for large number of keys (opt-in depending on how a board intends to use the kv). Could potentially decrease object overhead, but also lead to different design.

**Comment by wright-joe** [comment]
[Murmur3](https://docs.rs/murmur3/0.5.1/murmur3/)

**Comment by l162** [comment]
https://github.com/nickbabcock/highway-rs

**Comment by l162** [comment]
[Highway](https://docs.rs/highway/0.6.4/highway/)
