### ISSUE TITLE
Panic when flashing app with OpenOCD and arm-none-eabi-gdb on STM32F412GDiscovery

### ISSUE THREAD

**Issue by teonaseverin** [tock/tock#2432]
When flashing a kernel application on a STM32F412GDiscovery board with OpenOCD and arm-none-eabi-gdb, I get a 'Kernel HardFault', caused by an "Instruction Bus Error". The panic disappears after a reset. Is there any explanation for this?

Moreover, the panic is not printing anything on the console. I am using `cortex-m-semihosting` in the `src/io.rs` file in order to print the panic messages. 

The steps to reproduce this are the following:

terminal 1: `openocd -f openocd.cfg`

terminal 2: `arm-none-eabi-gdb app.elf` & `target remote :3333` & `monitor arm semihosting enable` & `load` & `continue`

**Comment by bradjc** [comment]
Maybe this is related to #1843?

I don't have any explanation or ideas why that might be occurring.
