### ISSUE TITLE
Tracking: AES system call driver

### ISSUE THREAD

**Issue by hudson-ayers** [tock/tock#2453]
Currently AES support only exists in the kernel, as the userspace driver was removed in https://github.com/tock/tock/pull/684 . It would be nice to bring back AES support in userspace. This issue tracks progress on that front and records pointers to old code that might be helpful in that task.

- [x] Create a userspace driver using the current symmetric encryption HIL, potentially based on https://github.com/tock/tock/pull/684#issuecomment-359839402
- [x] Create a libtock-c userspace driver to match the in-kernel one. The driver removed in https://github.com/tock/libtock-c/pull/188 may be a good starting point for this.

**Comment by bradjc** [comment]
Implemented in #2795
