### ISSUE TITLE
Tracking: Exit syscall polishing

### ISSUE THREAD

**Issue by hudson-ayers** [tock/tock#2473]
Tock 2.0 added an exit system call, and specified a mechanism for completion codes, such that the system call interface was specified at the 2.0 release. Some of the precise details of how the kernel will handle exit system calls is left for post-2.0. This tracking issue records remaining work on that front.

- [x] Store completion codes when `terminate()` is called in `process.rs`, possibly as some `Process::debug_` field (https://github.com/tock/tock/pull/2446/files#r583852537)
- [ ] Determine how to handle failed restarts in `Process::try_restart()` -- should process resources be immediately freed? Is additional error recording needed?

**Comment by bradjc** [comment]
I think we can close this. The remaining item is a fairly broad design question (reclaiming resources) and isn't really related to the exit syscall. I think we will eventually need to address what to do with system resources from failed processes, but I don't think that is related to exit.
