### ISSUE TITLE
Quick RFC: Tock Registers: `IntLike` to `UIntLike`

### ISSUE THREAD

**Issue by ppannuto** [tock/tock#2641]
#2623 highlighted that really our register interface lets us turn register operations into operations on well-defined unsigned numbers. We called this trait magic `IntLike`, presumably as we were saying that the underlying data could be manipulated like numbers, but I think the implementation is more accurately `UIntLike` (indeed, all of the example types are `u8`, `u16`, ...).

Since we're going to have some churn with this upcoming release, and since it will hopefully be a 1.0 interface, I'd propose we rename `IntLike` to `UIntLike`, both to more accurately reflect what's happening, and leave the door open to doing something intelligent in a non-breaking manner with registers that hold signed integer -like values in the future.

This should be a quick `s/IntLike/UIntLike` if we opt to make the change.

Thoughts? @lschuermann @andre-richter @bradjc @brghena

**Comment by lschuermann** [comment]
I think this is a good change. It just clarifies some things, and the other changes in the upcoming release are breaking existing code already, so I'm in favor of introducing this change now as well. Feel free to add a commit on to my PR, alternatively I can do that in ~4-5h when I'm back at my PC.

I'd be much more hesitant to introduce registers over signed integers or arbitrary types, but leaving this up for discussion and enabling to introduce this in a non-breaking manner is definitely a win.

**Comment by hudson-ayers** [comment]
+1 to this change

**Comment by andre-richter** [comment]
+1
