### ISSUE TITLE
Example on how to build/flash custom app on esp32-c3-devkitM-1

### ISSUE THREAD

**Issue by wassup-** [tock/tock#2811]
I'm having a hard time figuring out how to build and flash a custom app on a **esp32-c3-devkitM-1** board.
I followed the [setup instructions](https://github.com/tock/tock/tree/master/boards/esp32-c3-devkitM-1#setup) and successfully flashed Tock onto the board, but have no idea what to do next.

I can see in the [Makefile](https://github.com/tock/tock/blob/2910b12382dd8358d0bfced296e01442af5e7b80/boards/esp32-c3-devkitM-1/Makefile#L21) that there is support for flashing an app onto the board using `make flash-app`, but how should I build this app? I assume I have to use [libtock-rs](https://github.com/tock/libtock-rs), but they are referring to [tockloader](https://github.com/tock/tockloader) which I'm pretty sure I can't use because the **esp32-c3-devkitM-1** platform is not (yet) supported.

Can anyone point me in the right direction? I'd really love to try out Tock on my ESP32-C3 board.

**Comment by alistair23** [comment]
Hey,

You will want to use [libtock-c](https://github.com/tock/libtock-c) as libtock-rs doesn't work. You can build an example for libtock-c and then flash that to the board using the `make flash-app` target. 

When specifying the `APP` make sure you use the memory addresses from here: https://github.com/tock/libtock-c/blob/master/Configuration.mk#L71 and use the `tbf` file
