### ISSUE TITLE
Error loading processes! Process did not provide a TBF kernel version header

### ISSUE THREAD

**Issue by nicolast0604** [tock/tock#2814]
make OPENTITAN_BOOT_ROM=$OPENTITAN_TREE/build-bin/sw/device/boot_rom/boot_rom_fpga_nexysvideo.elf APP=~/tock/libtock-rs/target/riscv32imc-unknown-none-elf/tab/opentitan/hello_world/rv32imc.tbf qemu-app

encountered the follow error, please hint thanks a lot.

 Finished release [optimized + debuginfo] target(s) in 0.05s
   text	   data	    bss	    dec	    hex	filename
 100404	   8480	   9952	 118836	  1d034	/home/nicolast0604/tock/tock/target/riscv32imc-unknown-none-elf/release/earlgrey-nexysvideo
../../tools/qemu/build/qemu-system-riscv32 -M opentitan -kernel /home/nicolast0604/tock/tock/target/riscv32imc-unknown-none-elf/release/earlgrey-nexysvideo.elf -bios /home/nicolast0604/opentitan.backup.08042021/build-bin/sw/device/boot_rom/boot_rom_fpga_nexysvideo.elf -device loader,file=/home/nicolast0604/tock/libtock-rs/target/riscv32imc-unknown-none-elf/tab/opentitan/hello_world/rv32imc.tbf,addr=0x20030000 -nographic -serial mon:stdio
I00000 boot_rom.c:60] Version:    opentitan-earlgrey_silver_release_v5-201-g6562d954f
Build Date: 2021-09-07, 17:51:07

I00001 boot_rom.c:76] Boot ROM initialisation has completed, jump into flash!
Error loading processes!
Process did not provide a TBF kernel version header
OpenTitan initialisation complete. Entering main loop

**Comment by alistair23** [comment]
Unfortunately libtock-rs does not currently support Tock 2.0 so it won't work. You will need to use libtock-c apps instead or use the older Tock 1.6 release
