### ISSUE TITLE
Temperatures HIL disallows negative values

### ISSUE THREAD

**Issue by dcz-self** [tock/tock#2965]
Hi,

writing a driver for a temperature sensor, I noticed this:

```
/// Client for receiving temperature readings.
pub trait TemperatureClient {
    /// Called when a temperature reading has completed.
    ///
    /// - `value`: the most recently read temperature in hundredths of degrees
    /// centigrate.
    fn callback(&self, value: usize);
}
```

The problem is the `usize`, which is rather weird for 2 reasons:
1. Unsigned values are positive only, not leaving any way to represent negative temperatures, which are rather common in normal use.
2. usize has a size depending on the architecture rather than the sensor type

It can be fixed easily by replacing the `usize` with a `i32`.

Alternatively, the first issue can be fixed by reporting on the Kelvin scale. There's little danger of sensors existing in such extreme environments that they reach the negative part of that scale.

Would a replacement of `usize` with `i32` get accepted?

**Comment by hudson-ayers** [comment]
> Would a replacement of usize with i32 get accepted?

I would support that change. I don't think the temperature syscall API is stabilized

**Comment by dcz-self** [comment]
Submitted https://github.com/tock/tock/pull/2967

**Comment by alexandruradovici** [comment]
I would be in favor of returning the temperature in hundreds of K. This would be in compliance with the standard measurement unit.

**Comment by dcz-self** [comment]
Do we need a newtype for the temperature readout? I think one could be useful as a place to store documentation for what exactly the returned value represents.

**Comment by alexandruradovici** [comment]
I think using hundreds of K should be fine as long as it is documented in the HIL.

**Comment by alexandruradovici** [comment]
I think this not entirely true, as the suggested change is to wrap the value in an `Option<usize>`, which will make the compiler show an error everywhere it is being used.

**Comment by alexandruradovici** [comment]
On a second thought, if code size is not impacted, I could see an implementation similar to:

```rust
#[transparent]
struct TemperatureValue(usize);

impl TemperatureValue {
   pub fn as_kelvin(&self) -> usize {...}
   pub fn as_celsius(&self) -> usize {...}
}
```

**Comment by hudson-ayers** [comment]
I would advocate for just picking one of isize + celcius or usize + kelvin and sticking to that. If apps want one or the other they can handle the conversions themselves.
