### ISSUE TITLE
Cannot use `tock-registers` on the stable release channel

### ISSUE THREAD

**Issue by dawsonc623** [tock/tock#2982]
I am trying my hand at some embedded Rust development on a Raspberry Pi 4B, and one of my dependencies (`cortex-a`) depends on this library. My toolchain uses the stable release channel, and when trying to compile my project I get `error[E0554]: '#![feature]' may not be used on the stable release channel`. Is this by design, or is this library intended to work for devs using the stable release channel?

**Comment by alexandruradovici** [comment]
Can you point us to the exact crate that you are using and the crate (library) that it depends on from this repository?

**Comment by jrvanwhy** [comment]
> Can you point us to the exact crate that you are using and the crate (library) that it depends on from this repository?

I checked `cortex-a`'s `Cargo.toml`, and it depends on `tock-registers`. It may be easy to make `tock-registers` work on stable Rust (I might send a PR today).

**Comment by jrvanwhy** [comment]
I edited the issue title to mention `tock-registers`, so that Tock developers understand at a glance which library this issue refers to.

The overarching issue for making Tock build on stable Rust is https://github.com/tock/tock/issues/1654.

**Comment by dawsonc623** [comment]
Sorry, I should have dug a little deeper to give a better description (I did not realize this was a mono-repo and how big the scope of the project is). Thanks for making that clearer. I am not the most advanced Rust developer out there (especially in the embedded space), but if there is anything I can help with to get unblocked I am happy to try.

**Comment by jrvanwhy** [comment]
PR opened: https://github.com/tock/tock/pull/2983

The specific unstable feature in use is likely to be stabilized soon, and the PR I opened has some drawbacks, so it's possible that we will not merge the PR.

**Comment by jrvanwhy** [comment]
Making `tock-registers` work on stable Rust will not solve your issue on its own, because `cortex-a` depends on unstable Rust as well: https://github.com/rust-embedded/cortex-a/blob/fd6688419ac9884abd1d79a18b3ff64b4776e1f4/src/lib.rs#L82. It'll just move the compilation error from the `tock-registers` crate to the `cortex-a` crate.

**Comment by dawsonc623** [comment]
Hmmm, okay. Well, thanks for your work on this all the same. I will open an issue with `cortex-a` next and see what they say.

**Comment by brghena** [comment]
@dawsonc623 One thing to check, do you actually need to be on stable, or could you just move your toolchain to a nightly version of rust?

**Comment by dawsonc623** [comment]
@brghena That is a good point. The stable channel is preferred since that is what the team has set up, but I do not think there is any policy holding us to stable right now. I will check into that; thanks for the suggestion!

**Comment by jrvanwhy** [comment]
The consensus at #2983 was to wait for `feature(const_fn_trait_bound)` to be stabilized before moving `tock-registers` over to stable Rust. It sounds like moving to a nightly toolchain is a reasonable workaround in the meantime.

**Comment by jrvanwhy** [comment]
The stabilization PR for `feature(const_fn_trait_bound)` was merged: https://github.com/rust-lang/rust/pull/93827#event-6197814397. Unless it is reverted, `feature(const_fn_trait_bound)` will be stable in 1.61.0.

**Comment by qwandor** [comment]
Now that Rust 1.61 has gone to stable and #2988 is in, can we get a release of tock-registers that doesn't require nightly?

**Comment by qwandor** [comment]
Hi, any update on this? Could a release be pushed that supports building on stable?

**Comment by ppannuto** [comment]
Thanks for the nudge! Just opened #3151 — I'll push to crates.io once that's merged

**Comment by ppannuto** [comment]
And we're live!

https://crates.io/crates/tock-registers
