### ISSUE TITLE
Screen HIL docs and API contradictory

### ISSUE THREAD

**Issue by dcz-self** [tock/tock#3004]
From the docs file:

>     **Description**: Get the screen's resolution
>
>    **Argument 1**: unused
>
>    **Argument 2**: unused
>
>    **Returns**: Ok(()) followed by a callback with the resolution, BUSY if another command is in progress.

Meanwhile, the API:

```
    /// Returns a tuple (width, height) with the current resolution (in pixels)
    /// This function is synchronous as the driver should know this value without
    /// requesting it from the screen.
    ///
    /// note that width and height may change due to rotation
    fn get_resolution(&self) -> (usize, usize);
```

Those differences are all over.

Which one is behind? I'll fix it once I have it confirmed.

EDIT: never mind, those are the wrong things to compare.

**Comment by alexandruradovici** [comment]
The documentation is wrong, the comment is correct. I'll fix the documentation, thank you for pointing it out.
