### ISSUE TITLE
tock-registers: Allow setting registers by enum value

### ISSUE THREAD

**Issue by qwandor** [tock/tock#3012]
If I use the `register_bitfields` macro to declare a set of possible value for a register field, then I can use `Readable::read_as_enum` to get back a value of the appropriate `REG::FIELD::Value` enum type. However, unless I'm missing something, there doesn't seem to be any way to write such an enum value back into the field (i.e. to pass it to `write` or `modify`).

This could be solved by generating a `From` implementation for `FieldValue` alongside the generated enum type.

**Comment by alistair23** [comment]
You can just use the enum directly, like this: https://github.com/tock/tock/blob/master/chips/earlgrey/src/aes.rs#L442

**Comment by qwandor** [comment]
@alistair23 The code you linked doesn't seem to be using the enum type, only the constant `FieldValue` instances.
