### ISSUE TITLE
Does Tock support POSIX Interface? 

### ISSUE THREAD

**Issue by wjhtinger** [tock/tock#3015]
Many legacy software need posix, how to port them to tock?

**Comment by alexandruradovici** [comment]
Tock does not intentionally support the POSIX standard as is based on a very different kernel / user space interface. On the other hand, the libtock-c implementation does provide `newlib` which in turn provides a subset of the libc API.

**Comment by wjhtinger** [comment]
Thank your reply. 
Another quesiton，does Tock support theads in user space?  And, there is only one thead in kernel, right?

**Comment by alexandruradovici** [comment]
No, it does not support threads. What you can do (if you need only one extra thread) is start two process and use IPC between them.

**Comment by brghena** [comment]
And the kernel indeed only has one thread in Tock.

There are some basic thoughts on multi-core support, see #2873. Although no implementation yet.

**Comment by lschuermann** [comment]
Closing this as the original question seems to have been resolved.
