### ISSUE TITLE
Slightly confusing description of rust in the readme

### ISSUE THREAD

**Issue by nico-abram** [tock/tock#3028]
The readme states:
> are written in Rust, a systems programming language that provides compile-time memory safety, type safety and strict aliasing

I find this use of "strict aliasing" confusing. Rust has "strict" aliasing rules w.r.t &/&mut but isn't this is easy to misunderstand since in gcc -fno-strict-aliasing disables Type-Based Alias Analysis, and "Strict Aliasing" is somewhat overloaded as a term. But rust has no type-based aliasing rules (A `*mut T` and `*mut U` can alias. The only restrictions come from reference types (Or Box, or the unstable Unique<T>), but as far as I know those are closer to using C's `restrict` than type-based aliasing), rust memory is "untyped"

**Comment by lschuermann** [comment]
According to the [Rust Unsafe Code Guidelines Reference Glossary](https://rust-lang.github.io/unsafe-code-guidelines/glossary.html), _aliasing_ is defined as to occur "when one pointer or reference points to a "span" of memory that overlaps with the span of another pointer or reference." I think this is the definition we're implying in that statement.

> The only restrictions come from reference types

Indeed, the only case where aliasing as defined above is restricted in terms of soundness is with references. Perhaps we can rephrase to "[...] and strict reference aliasing rules."?

**Comment by jrvanwhy** [comment]
"strict aliasing" is a well-known term in the C/C++ world, but is not present in the Rust language.

I think we can shorten the sentence to:

> First, the kernel and device drivers are written in Rust, a systems programming language that provides compile-time memory safety and type safety.

From this perspective, Rust's aliasing rules aren't a feature -- they are a tool Rust uses to achieve its "memory safety" feature.
