### ISSUE TITLE
Have a way to *not* upgrade warnings to errors in CI

### ISSUE THREAD

**Issue by dcz-self** [tock/tock#3050]
I am currently maintaining a branch of Tock, which I intend to experiment on, and gradually upstream. With the amount of experimentation I did, I needed to take some technical debt, and my build has plenty of warnings.

The problem is with Tock upgrading warnings to failures behind my back, breaking the principle of least surprise.

When I run `make` on my laptop, it succeeds with warnings. When I run `make` in my local CI checker, it succeeds with warnings. When I run `make` in Gitlab CI, it suddenly changes its mind and fails: https://framagit.org/jazda/tock/-/jobs/1692651

I don't think this is good behaviour: the build system should not guess the intention of the person running it, because it will inevitably fail in some circumstances (as exemplified).

Moreover, there doesn't seem to be a way to override the mistaken detection. I tried to find when the detection happens, but my Makefile skills are not sufficient for that.

Could the automatic detection be replaced by an explicit setting of CI=true *outside* of the makefiles, so that it's controllable directly by the caller?

**Comment by dcz-self** [comment]
Yes, but for me, the logic is wrong for me. I did remove that part in my downstream, but I don't like increasing the diff.

The flawed guessing for what is "CI=true" and what isn't is something I can't find.

**Comment by dcz-self** [comment]
Oh, now I see, that's picked up from the runner environment. That makes things complicated, because the user no longer actually decides how things are being run, with runners typically being set up by someone else.

Working around users' bad infrastructure is not something projects should do, so I'll just suggest unhardcoding the assumption that CI means errors must be upgraded for everyone. That'll make downstream development easier.

**Comment by dcz-self** [comment]
Yes, be sensitive to a custom environment variable: "DISABLE_UPGRADE_WARNINGS". The "disable" means you don't have to change your CI configuration, so it would stand out in a contribution. Meanwhile, anyone who wants to make use of such a flag can add the variable in their favorite way (gitlab allows setting variables out-of-band, meaning I would be able to do it without altering code).

That's a middle-of-the-way position, because running the same command will give different results depending on the environment that might not be obviously different. A more total solution would be to introduce an environment variable "UPGRADE_WARNINGS" instead. It could be explicitly present in CI pipelines (stopping a mistaken change needs a reviewer to catch it), or implicitly in CI runner config (only admin can switch it).

**Comment by hudson-ayers** [comment]
Ok, I understand a little better what is happening now. Both github and gitlab automatically set an environment variable `CI=true` when running in the CI environment, so even though you are not running our predefined ci jobs you still are getting warnings treated as errors. This was also the case for Travis CI, our old CI platform.

I am not sure whether we are relying on this behavior for any other CI commands (i.e. are there any CI commands for which we do not currently manually pass `CI=true`, but for which warnings being treated as errors is important?). If not, the easiest fix here is probably just to rename our `CI` variable to something else (i.e. `TREAT_AS_CI` or similar).
