### ISSUE TITLE
Tock-Register support for compare-and-swap

### ISSUE THREAD

**Issue by AGSaidi** [tock/tock#3061]
I wanted to see if there would be any support for extending Tock-registers `InMemoryRegister` to support compare-and-swap(CAS) operations. Some in memory registers can be written by hardware with a CAS and to not lose bits, the software would also have to use a CAS. For example page tables that support hardware setting or clearing of bits while being modified by software need to do an atomic read-modify-write.

**Comment by AGSaidi** [comment]
https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#method.compare_exchange 

Even only supporting it on some architectures would be helpful. I'm happy to attempt an implementation if there is roughly agreement that it's desirable.

**Comment by hudson-ayers** [comment]
It should be possible to add this using target_feature or something similar to gate availability to platforms with atomic operations. I think it is probably fine to have operations which are only available to certain platforms for a library like tock-registers

**Comment by lschuermann** [comment]
I'd like to avoid using a feature flag, or anything global, for such an addition. While I see the usecase of supporting CAS instructions, I'm unsure as to whether these can _on every platform_ work _on all regions of memory_ and suspect that there may be some, for which it can only work on tightly coupled memory, for instance.

Furthermore, such instructions have a tendency to differ in semantics between architectures, and even if they do -- which seems to be the case for CAS generally -- they don't solve the overarching issue of atomicity and generally "special" instructions being unsupported in the `tock-registers` interface up to now. Take for instance RISC-V, which does not feature compare-and-swap, but does have atomic read & write, atomic read & set bits and atomic read & clear bits:

https://github.com/tock/tock/blob/99cf1d32ce05dfd96a98e8f6989c162e753bba57/libraries/riscv-csr/src/csr.rs#L130-L271

Some platforms may also want to support CAS through a global atomic register and spinlock, and wish to make that accessible through the `tock-register-interface`. Hence I think the best solution here could be optional extension traits, where we'd have traits such as

```
pub trait ReadWriteableCAS: ReadWriteable {
    fn compare_and_swap(&self, cmp: <Self as ReadWriteable>::T, write: <Self as ReadWriteable>::T) -> bool;
}
```

The beautiy of the `tock-register-interface` trait interfaces is that you can define custom types in your own codebase, using the architecture-specific implementations of whatever instructions shall be supported, and as long as it meets the requirements of a defined trait in the `tock_registers::interfaces` module, just implement this trait. An interface requiring an in-memory register with CAS semantics will then simply require some type `R: ReadWriteableCAS<T=impl IntLike, R=impl RegisterLongName>`. This trait must not necessarily be implemented in `tock-register-interface` itself, but shipping these traits in the crate increases interop.

Would that solve your issues, @AGSaidi?

**Comment by hudson-ayers** [comment]
I was not suggesting a feature flag that would be toggled, and was instead suggesting: 

```rust
// Below only evaluates to true if target architecture supports 32 bit CAS instructions
#[cfg(target_has_atomic = "32")]
fn compare_and_swap(&self, cmp: <Self as ReadWriteable>::T, write: <Self as ReadWriteable>::T) -> bool { 
    AtomicU32::compare_exchange(self, /*...*/);
}
```

I believe this would not enable using this function on RISC-V, for example, since it does not support 32 bit CAS, but would provide this function for-free on platforms with those instructions.

I think Leon's suggested approach also sounds fine though

**Comment by AGSaidi** [comment]
I was imagining what @hudson-ayers  said too. I've gone ahead and hacked this to try it both ways and found a couple of wrinkles. 

Implementing it outside of the crate doesn't seem possible because InMemoryRegister value is private and i need to be able to call self.value.get() to get a pointer for the atomic. 

Implementing it in the crate seems to work with one ugly issue. There isn't an easy way to write code for a generic atomic operation. The only way I've found to do it is to use `core::intrinsics::atomic_cxchg_relaxed()` which means depending on a feature to be able to access the intrinsic.  There does seems to possibly be a work around here of various macro-magic to spit out the right AtomicUxx type like was done with [atomic-rs](https://github.com/Amanieu/atomic-rs/blob/master/src/ops.rs#L16) or maybe using atomic-rs.

**Comment by hudson-ayers** [comment]
We would like to make tock-registers available on stable rust very soon, so requiring a feature will likely be a non-starter. I also do not think we want to add an external dependency here. Perhaps we could use something like the macro that you linked, though.

**Comment by AGSaidi** [comment]
>@AGSaidi I can provide you with a minimal example of what this would look like tomorrow. 

I didn't understand what you were proposing. Thanks for the offer, but i think i can make that happen, let me give it a try.

**Comment by bradjc** [comment]
Please re-open if this is being worked on.
