### ISSUE TITLE
nRF52840-DK's Board Configuration Leaves 63.5Mb of storage unavailable

### ISSUE THREAD

**Issue by TheConner** [tock/tock#3098]
The nRF52840-DK's storage is configured [here](https://github.com/tock/tock/blob/master/boards/nordic/nrf52840dk/src/main.rs#L570-L573), partitioning out `0-0x60000` (384 Kb) for the kernel space storage region, and then `0x60000-0x80000` (128 Kb) for userspace storage region. Using the [nonvolatile storage test application](https://github.com/tock/libtock-c/tree/master/examples/tests/nonvolatile_storage) on the nRF52840-DK, I see only 128 Kb for userspace which is expected under this configuration.

This amount of storage makes sense if Tock was only using the nRF52840's flash storage (1MB total, iirc); however, the nRF52840-DK has 64Mb of [external storage](https://infocenter.nordicsemi.com/topic/ug_nrf52840_dk/UG/dk/hw_external_memory.html) on a [MX25R6435F SPI/QSPI flash chip](https://www.macronix.com/Lists/Datasheet/Attachments/8746/MX25R6435F,%20Wide%20Range,%2064Mb,%20v1.5.pdf). It seems that the `NonvolatileStorageComponent` for the nRF52840-DK [is configured to use the external flash chip](https://github.com/tock/tock/blob/master/boards/nordic/nrf52840dk/src/main.rs#L566-L569), so it should define a larger userspace flash region (or both userspace and kernel space) to enable access to the other 63.5 Mb of flash storage.

My suggestion is to increase the flash regions as follows, to fill all 64Mb of external flash (will follow up with a PR for this)

Kernel: 0-0x60000 (384 Kb, the same amount)
Userspace: 0x60000-0x4000000 (63.625 Mb, fill the rest of available flash)

**Comment by hudson-ayers** [comment]
Fixed by #3099 . Thanks!
