### ISSUE TITLE
why is tock,not linux?

### ISSUE THREAD

**Issue by elderbig** [tock/tock#3304]
which scene should I use tock ?

**Comment by brghena** [comment]
Tock is really designed for microcontroller-based systems which are often uncapable of running a larger OS like Linux. Particularly, the systems that we run on typically don't have Virtual Memory, which Linux requires for safety.

One place to read a lot of background on this is in the paper we wrote on Tock: https://dl.acm.org/doi/pdf/10.1145/3132747.3132786 Particularly, check out section 2 which includes background and motivation for Tock.
