### ISSUE TITLE
raspberry_pi_pico debug build fails with rust-lld error

### ISSUE THREAD

**Issue by CarlosRFS** [tock/tock#3313]
When i  build TockOS to raspberry_pi_pico with make it builds normally, but when i try to build with make V=1 debug i have some rust-lld errors like this:
rust-lld: error: section '.text' will not fit in region 'rom': overflowed by 3 bytes

the entire log its in the link bellow
https://pastebin.com/ecnrHtq5

**Comment by hudson-ayers** [comment]
#3314

**Comment by CarlosRFS** [comment]
thanks @alexandruradovici
