### ISSUE TITLE
RFC: Reorganizing capsules into `core/`, `contrib/`, `external/`

### ISSUE THREAD

**Issue by hudson-ayers** [tock/tock#3346]
On last week's core call we discussed making capsules not a single crate, but a few crates. There are several benefits to this, the motivating one from the call was so that we could have a dedicated crate for capsules with external dependencies. I believe the conclusion we came to on the call was to minimize the amount that we split up `capsules` to start by just making two crates -- `core/`, for core capsules we expect almost all boards to use, and `contrib/`, for everything else. Finally, there would be an `external/` directory which would hold individual crates for each capsule with external dependencies. 

We did not come to a conclusion on exactly how we would split up `core/` and `contrib/`. I would like some level of agreement before I implement this, since it is going to require renaming a ton of paths, so lots of changing back and forth will be a pain. I propose the following breakdown:

## Core:
adc.rs
alarm.rs
button.rs
console.rs
gpio.rs
led.rs
i2c_master.rs
i2c_master_slave_driver.rs
low_level_debug/
process_console.rs
rng.rs
spi_controller.rs
spi_peripheral.rs
virtual_adc.rs
virtual_aes_ccm.rs
virtual_alarm.rs
virtual_digest.rs
virtual_flash.rs
virtual_hmac.rs
virtual_i2c.rs
virtual_pwm.rs
virtual_rng.rs
virtual_sha.rs
virtual_spi.rs
virtual_timer.rs
virtual_uart.rs

## Contrib:
adc_microphone.rs
air_quality.rs
ambient_light.rs
analog_comparator.rs
analog_sensor.rs
apds9960.rs
app_flash_driver.rs
ble_advertising_driver.rs
bme280.rs
bmp280.rs
bus.rs
buzzer_driver.rs
buzzer_pwm.rs
ccs811.rs
crc.rs
ctap.rs
dac.rs
debug_process_restart.rs
fm25cl.rs
ft6x06.rs
fxos8700cq.rs
gpio_async.rs
hd44780.rs
hmac.rs
hts221.rs
humidity.rs
ieee802154/
isl29035.rs
kv_driver.rs
kv_store.rs
l3gd20.rs
led_matrix.rs
log.rs
lpm013m126.rs
lps25hb.rs
lsm303agr.rs
lsm303dlhc.rs
lsm303xx.rs
lsm6dsoxtr.rs
ltc294x.rs
max17205.rs
mcp230xx.rs
mlx90614.rs
mx25r6435f.rs
net/
ninedof.rs
nonvolatile_storage_driver.rs
nonvolatile_to_pages.rs
nrf51822_serialization.rs
panic_button.rs
pca9544a.rs
proximity.rs
public_key_crypto/
read_only_state.rs
rf233_const.rs
rf233.rs
screen.rs
sdcard.rs
segger_rtt.rs
seven_segment.rs
sha256.rs
sha.rs
sht3x.rs
si7021.rs
sip_hash.rs
sound_pressure.rs
st77xx.rs
symmetric_encryption/
temperature_rp2040.rs
temperature.rs
temperature_stm.rs
text_screen.rs
tickv.rs
touch.rs
tsl2561.rs
usb/

Any thoughts appreciated! I am certainly not married to this division.

Main questions I have:
1. Should some of the less-used virtualizers (virtual_{aes/flash/hmac/sha/pwm}) be in `contrib/`?
2. Should the i2c/spi drivers be in core or contrib? Most of our boards don't expose these userspace drivers now
3. Do we want to include any sensor drivers in core? ninedof, for example?

**Comment by hudson-ayers** [comment]
cc @tock/core-wg

**Comment by lschuermann** [comment]
For what it's worth, here are the notes of the relevant discussion: https://github.com/tock/tock/blob/54c8045099dd46fb30f44978af5495a99a83008a/doc/wg/core/notes/core-notes-2022-12-02.md#policy-on-external-dependencies-pr-3312

**Comment by phil-levis** [comment]
> Should some of the less-used virtualizers (virtual_{aes/flash/hmac/sha/pwm}) be in `contrib/`?

I agree that they *should* be in core, but I don't think all of them have received the same degree of scrutiny. So perhaps we should give each one a reviewer who can go over and polish them a bit.

> * Should the i2c/spi drivers be in core or contrib? Most of our boards don't expose these userspace drivers now

These seem like core -- they are often very useful for bringing up drivers in userspace.

> * Do we want to include any sensor drivers in core? ninedof, for example?

I'd say no.

**Comment by phil-levis** [comment]
> `core/`, for core capsules we expect almost all boards to use, and `contrib/`, for everything else

I suppose I might articulate this as "capsules that are broadly and commonly useful across boards" and "everything else." It might sense to call `contrib/` something else, though, like `extra`?

**Comment by alevy** [comment]
Agree with @phil-levis on all of his responses.

**Comment by hudson-ayers** [comment]
I like `extra`. Thanks for all the feedback, I think this is enough for me to move forward.

**Comment by alistair23** [comment]
This issue can be closed now that https://github.com/tock/tock/pull/3396 is merged
