### ISSUE TITLE
License headers: interpretation of "blank line"?

### ISSUE THREAD

**Issue by jrvanwhy** [tock/tock#3383]
[`trd-legal.md`](https://github.com/tock/tock/blob/master/doc/reference/trd-legal.md) says:

> License and copyright information SHOULD have at least one (1) blank line separating it from any other content in the file.

When I implemented the license checker, I interpreted this as prohibiting `//` and `#` symbols in the blank line. However, four files in the repository have a `//` line:

[`chips/stm32f4xx/src/can.rs`](https://github.com/tock/tock/blob/master/chips/stm32f4xx/src/can.rs)
[`boards/components/src/can.rs`](https://github.com/tock/tock/blob/master/boards/components/src/can.rs)
[`kernel/src/hil/can.rs`](https://github.com/tock/tock/blob/master/kernel/src/hil/can.rs)
[`capsules/src/can.rs`](https://github.com/tock/tock/blob/master/capsules/src/can.rs)

We need to clarify which interpretation of "blank line" is correct. Should we remove the `//` symbols from the above four files, or adjust the license checker to accept the `//` symbols?

**Comment by hudson-ayers** [comment]
I would vote for it being a truly blank line (e.g. no `//` etc.) but don't feel strongly about this.

**Comment by brghena** [comment]
No one felt super strongly about this, and most of us didn't care at all. The conversation led to a decision to be permissive whenever possible, so accepting both blank lines and commented lines seems like the right choice.
