### ISSUE TITLE
requesting code review for kernel::scheduler::mlfq::MLFQSched::redeem_all_procs

### ISSUE THREAD

**Issue by D0x45** [tock/tock#3389]
I was reading the codebase and i stumbled upon this:
https://github.com/tock/tock/blob/cfd0cdb492f6414e990b15747f5be7434589dc9d/kernel/src/scheduler/mlfq.rs#L93-L105
i do believe that this code does not do what it was intended to
(i can't get to build the kernel, so i did not test it)
even though i'm a beginner in Rust, i was thinking maybe this would be a better approach: (?)
```rust
    fn redeem_all_procs(&self) {
        for queue in self.processes.iter().skip(1) {
            match queue.pop_head() {
                Some(proc) => self.processes[0].push_tail(proc),
                None => continue,
            }
        }
    }
```

**Comment by brghena** [comment]
The use of `first` there sure looks like a bug to me! Well spotted. I think no one is actually using the MLFQ scheduler in practice.

We would certainly welcome a PR for this change, if you'd like to write one.

**Comment by hudson-ayers** [comment]
Yeah I agree that your fix is correct, please feel free to submit a PR!
