### ISSUE TITLE
Expand file type support in the license checker.

### ISSUE THREAD

**Issue by jrvanwhy** [tock/tock#3417]
Linker scripts do not support line comments (`//`-style comments). The license checker should support linker scripts, and should therefore be adjusted to support block comments as well.

Before implementing, I'll check whether there are other file types in the repository that only support block comments and make sure the implementation works for those too.

**Comment by jrvanwhy** [comment]
Okay, I've expanded this issue somewhat, as I've found other files the license checker doesn't work on.

Some of the `.jlink` files use Unix line endings, other use DOS (CRLF) line endings. Currently this breaks the license checker, as it was only designed for Unix line endings. I'm a bit torn on how to resolve this. My personal preference is to convert those files to Unix line endings, but I could also adjust the license checker to support CRLF files.

**Comment by jrvanwhy** [comment]
Oh, here's another file type that only supports block comments: XML

**Comment by hudson-ayers** [comment]
+1 for all Unix line endings
