### ISSUE TITLE
TicKV Database User Friendly Extension for Tock

### ISSUE THREAD

**Issue by bradjc** [tock/tock#3480]
Because TicKV uses hashed keys, it's hard for users to inspect a TicKV database in flash. Tockloader can show the contents of a TicKV database:

```
❯ tockloader tickv dump

REGION 0

REGION 1

REGION 2

REGION 3

REGION 4
TicKV Object hash=0x7bc9f7ff4f76f244 version=1 flags=8 valid=True checksum=0x1d7432bb
  Value:
TicKV Object hash=0x9efe426e86d82864 version=1 flags=8 valid=True checksum=0xd2ac393f
  TockTicKV Object version=0 write_id=0 length=16
    Value: a2a4a6a6a8aaacaec2c4c6c6c8caccce
TicKV Object hash=0x1cde83ca4e9906e4 version=1 flags=8 valid=True checksum=0xbf4c71c2
  TockTicKV Object version=0 write_id=0 length=21
    Value: 6963616e73656576616c75656275746e6f746b6579

REGION 5

REGION 6
...
REGION 22

REGION 23

REGION 24
TicKV Object hash=0x535dc75243578318 version=1 flags=8 valid=True checksum=0x102cab4e
  TockTicKV Object version=0 write_id=0 length=21
    Value: 6963616e73656576616c75656275746e6f746b6579

REGION 25
...
```

But unless a user remembers what string they used to store each object, they can only use the hashed value to retrieve the object. This sort of removes the benefit of using a hash in the first place.

In a production setting having hashed keys like this is probably fine. However, for debugging and experimentation it would be more user-friendly to be able to show the original key.

## RFC

I would like to at least support in Tockloader a way to show a TicKV database that preserves the original keys so users have an easier time querying them.

### Idea 1: Store the key string as another object

One idea I have on how to do this is to add two objects on an `tickv::append`:

1. The original key value: key=`<key>`, value=`<value>`
2. A copy of the original key: key=`H(<key>)`, value=`<key>`

On a `tickv::dump`, for each object tockloader would look for a matching object by hashing the stored key hash and using that as a new key. If found, the value of that object would be the original key. Tockloader would then format the output to show the original key to the user.

#### Pro

- Changes could be completely contained to Tockloader, no need to update the kernel at all.

#### Con

- Would be a tockloader hack/convention, which could be confusing.
- Extra overhead of storing an additional object for the key string.

### Idea 2: add key string to the tock tickv header

Tock objects in TicKV have a header to 1) include a write_id for access control, and 2) include a length to decouple the stored value from the length of the buffer. We could add to this header to support encoding the key string.

#### Pro

- Formalizes this idea, makes it clear how the key string is stored.
- Clear that it only applies to tock objects (not all tickv databases).
- Only store the key, no extra overhead.

#### Con

- Somewhat more difficult to implement variable length headers in rust/tock.
- Hard to support arbitrarily long keys given buffer sizes.
- Requires changes to the kernel.
- Not all users may want this.

### Idea 3: Idea 2, but add a new tock storage header version

We could do idea 2, but only in, say, version 1 of the tock storage header. Then it would be possible to support adding key strings or not.

#### Pro

- Makes this feature optional.

#### Con

- Adds additional complexity in the kernel.
- Might not be clear to users which to use.

## Thoughts?

I bring this up because I'm curious if how valuable something like this would be. I don't think it is worth adding this in the kernel if there are few uses cases beyond just debugging/ease of use.

**Comment by alistair23** [comment]
So! I think this is a really bad idea for anything other then debugging.

Basically the idea of hashing the keys is that then we don't need to store the keys, which can be very long. The original idea of TicKV was to store data where a key could be an arbitrary string. We don't want to be storing that in flash. I think this ends up apply for lots of use cases, where storing the key value is a large waste of space.

For debugging I do see the benefit though. In which case idea 1 seems like the best bet. I'm not convinced it's worth doing, but I think it's an acceptable solution if we want users to be able to see the original keys via Tockloader.

One other idea is to supply Tockloader with the keys. I suspect in lots of debug cases the user will have a small known list of keys. You could provide Tockloader this list, which it can then hash and compare to what is in flash. This can't lookup all keys, but might help get most of them, especially in debug/test situations.
