### ISSUE TITLE
`kv_system` HIL: why is the hashed key the full buffer?

### ISSUE THREAD

**Issue by bradjc** [tock/tock#3495]
In the KV HIL, the `generate_key()` function takes in a buffer for the key without a length:

https://github.com/tock/tock/blob/b28fcfb601846ee0d3e5a4605e4c5f149d5cbdf5/kernel/src/hil/kv_system.rs#L165-L176

In practice this makes the resulting hash dependent on the size of the static buffer that the board happened to use.

However, in our implementation of the kv_system HIL, the buffer is converted to a leasable buffer before being passed to the hasher:

https://github.com/tock/tock/blob/b28fcfb601846ee0d3e5a4605e4c5f149d5cbdf5/capsules/extra/src/tickv.rs#L395-L417

Is there a reason to not use `LeasableMutableBuffer` in the kv_system trait?

**Comment by alistair23** [comment]
I don't think there is a reason, we probably should use `LeasableMutableBuffer`

**Comment by bradjc** [comment]
This has been fixed.
