### ISSUE TITLE
Derive Debug on tock_registers Value

### ISSUE THREAD

**Issue by andreeaflorescu** [tock/tock#3670]
Is there any reason for not deriving `Debug` on `Value`? I think it would be nice to have debug so that we can use `unwrap` on `read_as_enum`, which would simplify the code. If there is no technical reason for not having Debug, I can work on a patch to add this.

**Comment by bradjc** [comment]
Seems fine to me.

**Comment by lschuermann** [comment]
Apologies for my delayed response! We had this come up in the past, and IIRC the line of argument as to why we didn't implement `Debug` was that this is an easy way to accidentally generate a lot of code that increases flash size (e.g., when you print a register with `debug!`).

However, that's not a particularly good argument, given that there are many other ways to increase flash utilization accidentally. So I think this is a good change.
