### ISSUE TITLE
Add an Asynchronous Process Loader

### ISSUE THREAD

**Issue by bradjc** [tock/tock#3828]
Tock supports a synchronous process loader with the following signature:

```rust
pub fn load_processes<C: Chip>(kernel, processes, ...) -> Result<(), ProcessLoadError>
```

This matches the common use case: simple process loading only requires parsing flash, creating a `Process` struct, and iterating through flash. No split-phase operations are required and a synchronous function works fine.

However, as we fill-in Tock features trying to use a synchronous loader with an async OS is increasingly tenuous. The major change is adding credentials and credential checking, which _does_ support split-phase operations (for example to verify a RSA signature). This leads to two challenges.

### Challenges

1. Errors are hidden. In general, a board's main.rs file does not know if any processes failed to load or why. With the sync interface, an error happens on a significant error (e.g. we are out of RAM), but not on a minor error (a process requires a different kernel version). Since the `load_processes()` function can only return once, only significant errors are reported.

    This is more challenging with credential checking, since boards have no idea if any processes failed credential checks.

2. `ProcessStandard` structs are created, even if the process is not approved. Because of how processes are loaded, a process is first created, allocated RAM, etc., and _then_ checked if the system approves it. In theory if the app is not approved (i.e. credentialed correctly) the kernel could recover these resources. But in practice we don't support that and doing so would require additional machinery.

### Proposal

We add an asynchronous process loader. This would generally follow how we create HILs, and include a client interface to notify boards of any process loading failures. The implementation would do credential checking before creating a `ProcessStandard` struct.

Like all process loaders, this would be optional for boards to use. Boards could still use the synchronous version.

**Comment by lschuermann** [comment]
As a side note, one cool new feature this could enable is loading processes from (external) flash into RAM for chips or architectures that do not have XIP flash. I'm not sure whether this is impossible with the current architecture, but it might just be something to consider if we were redesigning these interfaces.

**Comment by bradjc** [comment]
> As a side note, one cool new feature this could enable is loading processes from (external) flash into RAM for chips or architectures that do not have XIP flash. I'm not sure whether this is impossible with the current architecture, but it might just be something to consider if we were redesigning these interfaces.

That would certainly require async, and having a framework for async process loading would make extending to that case much easier.

**Comment by alevy** [comment]
I agree with this proposal broadly, but just a nit:

> This is somewhat historical: simple process loading only requires parsing flash, creating a Process struct, and iterating through flash. No split-phase operations are required and a synchronous function works fine.

I don't think this is purely "historical," in particular the most widely deployed use-case of Tock only has this exact model. Indeed, there is no credential checking, etc, for each process binary and everything should load before starting (or at least its perfectly fine to block starting to run until everything has loaded).

It is probably worth retaining the ability to do that simple version, even if many use-cases will only ever load things asynchronously.
