### ISSUE TITLE
CI-Nightly Syntax Error

### ISSUE THREAD

**Issue by brghena** [tock/tock#3962]
I think #3932 must have made some kind of error in `.github/workflows/ci-nightly.yml`.

Whenever I make a PR now, I get an error like this: https://github.com/tock/tock/actions/runs/8665351775/workflow stating that there is a syntax error on line 76. I'm not familiar with the syntax or structure though, so I'm not entirely sure what's wrong

**Comment by brghena** [comment]
@alevy You created the file and maybe this is an easy fix?

**Comment by bradjc** [comment]
I think this is fixed.
