### ISSUE TITLE
tock: rewrite in Swift

### ISSUE THREAD

**Issue by Samir-Rashid** [tock/tock#4062]
All aboard the new [Embedded](https://github.com/swiftlang/swift/blob/main/docs/EmbeddedSwift/UserManual.md) [Swift](https://github.com/swiftlang/swift-evolution/blob/main/visions/embedded-swift.md) hype train.

<sup>This is a joke</sup>

**Comment by lschuermann** [comment]
I agree; Rust has become much too stable for us recently. This should be a swift consideration.
