### ISSUE TITLE
Doc: -Z unstable-options --document-hidden-items causes `Kernel` struct to not be documented.

### ISSUE THREAD

**Issue by bradjc** [tock/tock#4064]
Currently on https://docs.tockos.org/kernel/, there is no documentation for the `Kernel` struct:

<img width="462" alt="image" src="https://github.com/tock/tock/assets/1467890/9365cdb8-9efc-48d8-879f-7ad511fbb0aa">

That `Kernel` type is not a link.

However, when built locally:

```
cd tock/kernel
cargo doc
open ../target/doc/kernel/index.html
```

It looks as expected:

<img width="594" alt="image" src="https://github.com/tock/tock/assets/1467890/01b6de37-afec-4729-b690-5ea8530dec2c">

I tracked this down to using the `-Z unstable-options --document-hidden-items` flag. If I include that when building kernel docs I get the undocumented `Kernel` struct.

**Comment by lschuermann** [comment]
It's hilarious that an option to document more can cause Rustdoc to generate _less_ docs. :upside_down_face:

**Comment by bradjc** [comment]
The fix might be to change to `cargo doc --document-private-items` which is perhaps what we actually wanted.
