### ISSUE TITLE
The explanation of the size of the generated binary？

### ISSUE THREAD

**Issue by heisen-li** [tock/tock#4253]
I ran `make` under the directory `boards/qemu_rv32_virt` to compile. Got the following results:

```
text    data     bss     dec     hex  filename
84480      12   40000  124492   1e64c ./qemu_rv32_virt
```
Here it shows that the `.text` field takes up 84,480 bytes (about 82.5 KB).

I further analyzed it using the tool `cargo bloat` mentioned in the tock website blog, which shows the following results:

```
Analyzing target/riscv32imac-unknown-none-elf/release/qemu_rv32_virt

File  .text    Size Crate
0.5%  19.8% 16.3KiB kernel
0.4%  15.4% 12.7KiB capsules_core
0.2%   9.4%  7.8KiB qemu_rv32_virt
0.2%   8.3%  6.8KiB core
0.1%   5.2%  4.3KiB virtio
0.1%   3.6%  3.0KiB rv32i
0.1%   3.1%  2.6KiB [Unknown]
0.1%   2.9%  2.3KiB std
0.0%   2.1%  1.7KiB capsules_system
0.0%   1.8%  1.5KiB riscv
0.0%   1.5%  1.2KiB compiler_builtins
0.0%   0.8%    712B qemu_rv32_virt_chip
0.0%   0.8%    702B components
0.0%   0.2%    192B tock_tbf
0.0%   0.1%     66B sifive
2.4% 100.0% 82.3KiB .text section size, the file size is 3.4MiB
```
If I understand correctly, the size of `text` shown here is the same as the result above.However, if the size column is summed (roughly 61KB), this figure is rather different from 82.3KB.I would like to know what is the content of this 20KB?How should it be interpreted?Does it have anything to do with the linker or memory layout?

**Comment by bradjc** [comment]
I think the extra space is read-only data. Looking at the addresses two symbols from the linker file:

https://github.com/tock/tock/blob/50f36b3ccba7d8187e4c005da18999bab5235be1/boards/build_scripts/tock_kernel_layout.ld#L117-L144

```
❯ readelf.py ../../target/riscv32imac-unknown-none-elf/release/qemu_rv32_virt.elf -lSs | grep _srodata
 34456: 8000f33a     0 NOTYPE  GLOBAL DEFAULT    2 _srodata
❯ readelf.py ../../target/riscv32imac-unknown-none-elf/release/qemu_rv32_virt.elf -lSs | grep __preinit_array_start
 34466: 80014390     0 NOTYPE  GLOBAL DEFAULT    2 __preinit_array_start
```

I think the difference is about 20KB.
