### ISSUE TITLE
Current DRIVER_NUM constant does not support multiple copies of the same driver

### ISSUE THREAD

**Issue by adkinsjd** [tock/tock#654]
I was catching signpost up yesterday and realized that the current way of identifying driver numbers in the board file does not support multiple of the same driver. This is a concrete problem in signpost where we have multiple i2c_selectors with different addresses, but you could imagine having multiple copies of any chip on a board, and a single driver number will not suffice.

This same problem bubbles up to userland drivers. Currently signpost has it's own userland driver that handles multiple i2c_selectors, and it's not clear there is an easy generic interfaces that would enable this.

**Comment by alevy** [comment]
You don't _have_ to use this style for non-standardized drivers, you can make up whatever driver number you want, however you want. For signpost, it probably makes sense to have _some_ constants defined somewhere that just give a name to the number, e.g. `I2C_SELECTOR_DRV_0`, `I2C_SELECTOR_DRV_1` etc.

The use of constants that are defined in the capsule module itself in the standardized drivers is just to make it easy to use the right driver number for those drivers.
