### ISSUE TITLE
Units are not specified in the generic sensor interfaces

### ISSUE THREAD

**Issue by adkinsjd** [tock/tock#655]
None of temperature, ambient_light, or humidity userland drivers specify units. Are they intended to standardize units?

**Comment by alevy** [comment]
Yes. They are specified in the `docs/syscalls` folder, but we should add them to documentation in `libtock` as well

**Comment by mwilbur** [comment]
Is there still interest in this work being done?

**Comment by alevy** [comment]
If they are still not documented in [tock/libtock-c](//github.com/tock/libtock-c), then yes.

**Comment by mwilbur** [comment]
Looks like they are not.  Any preferred way of doing it?  Header file?  C file?

**Comment by alevy** [comment]
Definitely in the header files.

**Comment by ppannuto** [comment]
Looks like this was long-since handled by https://github.com/tock/libtock-c/pull/37
