### ISSUE TITLE
Don't generate asm listing in debug target

### ISSUE THREAD

**Issue by Grawp** [tock/tock#731]
https://github.com/helena-project/tock/blob/27f45c54705c92ae9c7967634bdc14a48de6997f/boards/Makefile.common#L153

It is considerably slowing the debug builds and there is already **lst** target in the Makefile.

Moreover if you use `xargo` generating [unoptimized + debuginfo] sysroot (i.e. xargo compiled with _dev_ feature) the listing generation takes tens of minutes which renders the **debug** target unusable.

**Comment by alevy** [comment]
I am personally in favor of this (I always just use objdump anyway), but this has been hotly* debated on the past.

*Our debates are never really very hot. I also personally never use the debug builds.

**Comment by ppannuto** [comment]
A quick interlude independent of decision here, are you running on a Mac? It's known to be artifically slow and there's a fix for that here: https://github.com/helena-project/tock/blob/master/doc/Getting_Started.md#heads-up

**Comment by brghena** [comment]
I'm also just fine with the `lst` target being removed from the debug build, especially if it's causing problems for you. Over time it's been added back in / removed somewhat randomly.

One question for you, is what you are using the debug build for? For example, I'm fine with `lst` targets being run in debug builds since I only build in debug mode when I need to actually debug a particular problem, which too often seems to involve reading through some assembly too. But we should make sure that the semantics of `make debug` match what users are doing with it, which is possibly not the same as me.

**Comment by Grawp** [comment]
@brghena I use _Visual Studio Code_ (the opensource javascript thingy, not _Visual Studio_) with [native debug](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) and [rls-vscode](https://github.com/rust-lang-nursery/rls-vscode) to visually step through the tock code in order to learn how tock works or to help me with porting effort.

I've thought that was the point of debug build i.e. same as in C/C++ development for MCU. You connect via SWD or JTAG, place breakpoints in your code, interrupt handlers, wherever and then step in/over/out, observe variables, registers content etc. in your IDE.

(I also use xargo with "dev" feature on, as I've written above, which generates debug build of sysroot so I can also step through *core* library. But it shouldn't be necessary. I haven't tried linking unoptimized rust code with optimized sysroot yet though.)

I certainly don't want `lst` target removed. I just want to suggest to separate generating listing from `debug` target i.e. make two targets `debug` and `lst-debug` or something like that.
It's not much of an issue for me to keep having it locally patched.

**Comment by brghena** [comment]
Yeah, I'm fully in favor of this change then. The debug build should support JTAG without taking a ridiculous amount of time, and having a `lst-debug` target (or something like that) is easy enough to use.

**Comment by bradjc** [comment]
Did this ever get added?

**Comment by ppannuto** [comment]
https://github.com/helena-project/tock/blob/3333dbac72aa7c70731480d9d3514817e6081e3b/boards/Makefile.common#L158

Looks like no
