### ISSUE TITLE
Tracking: nRF5x to new register interface

### ISSUE THREAD

**Issue by bradjc** [tock/tock#809]
nRF51:

- [x] clock (#1123)
- [x] radio (#1125)
- [x] uart (#1053)

nRF52:

- [x] clock
- [x] ficr (#860) 
- [x] i2c (#965)
- [x] nvmc (#861) 
- [x] radio
- [x] spi (#966)
- [x] uart (#797)
- [x] uicr (#858)

nRF5x:

- [x] rtc (#969)
- [x] timer (#968)
- [x] aes
- [x] gpio (#867)
- [x] temp (#840)
- [x] rng

**Comment by ppannuto** [comment]
🎉
