### ISSUE TITLE
How about use relibc instead newlib

### ISSUE THREAD

**Issue by lygstate** [tock/tock#812]
relibc is a rust re-implementation of newlib, I thought it's would suite for tock.

https://github.com/redox-os/relibc

**Comment by bradjc** [comment]
This limited supported architectures seems problematic? https://github.com/redox-os/relibc#supported-architectures

**Comment by lygstate** [comment]
a long term investigation， we do not need to use relibc at this moment

**Comment by ppannuto** [comment]
I think we can close this. We've split the rust userland out to its own repository, here https://github.com/tock/libtock-rs, and when redox is a little more ready for primetime I think that'd be the right place to work towards integrating this.
