### ISSUE TITLE
NRF52 UART Receive

### ISSUE THREAD

**Issue by dcellucci** [tock/tock#893]
Hello, 

Working with the example in #851 I realized that `/chips/nrf52/src/uart.rs` doesn't implement the receiver behavior. 

1. Is anyone already working on this? If not, I'll get started.
2. What would be the best way of going about sending this changes out for a PR, since I'd like to use the #851 code to test my implementation. Separate PR? 

Thanks! 
DC

**Comment by alevy** [comment]
@dcellucci yes separate PR (which I see you've done), though I do think #851 is close to ready.
