### ISSUE TITLE
Alarm Capsule should do a check in a loop

### ISSUE THREAD

**Issue by bradjc** [tock/tock#905]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/1467890/39260450-905a0d76-4887-11e8-86c2-718f6575a3e7.png">

**Comment by bradjc** [comment]
I think this is actually OK as is.

https://github.com/tock/tock/blob/0ba03dd809e3b41ac5d28d816d95c95eee2872c2/capsules/src/alarm.rs#L184-L189

calls `reset_active_alarm` which, as implied, provides the next alarm sorted by expiration time. 

https://github.com/tock/tock/blob/0ba03dd809e3b41ac5d28d816d95c95eee2872c2/capsules/src/alarm.rs#L48-L71

Therefore if that alarm _hasn't_ expired, then no other alarms have expired, either. If that alarm _has_ expired, then it recursively calls the `fired()` method, which will run the same check again, and check the next timer (if it exists) and if that one has fired as well, then it will recurse as well. I believe the recursion handles the loop.

Does that make sense?

**Comment by brghena** [comment]
Oh, yeah, that does make sense to me. I hadn't realized the recursive `fired()` call was in there.
