### ISSUE TITLE
6lowpan Test Transmission Bug

### ISSUE THREAD

**Issue by jlwatson** [tock/tock#912]
Hi everyone,

While taking a crack at the hardcoded delay loops in the `ipv6_lowpan_test` code (discussed in #617), I've noticed that every so often (approximately once per test run, ~1/84 packets) the RF233 driver reports a successful transmission but neither the packet sniffer nor the receiver receives it and the overall test hangs. I'm still working on a fix but I wanted to give a heads-up as the 6loWPAN merge goes in.

#### Testing code

My working setup is pushed to Paul's fork [here](https://github.com/ptcrews/tock/tree/sixlowpan_library_test_delay) -- it essentially looks like this on two imixes, one receiving, one transmitting.

```
+------------------------------+                   +------------------------------+
|                              |                   |                              |
|         Transmitter          |                   |          Receiver            |
| MAC: 10:11:12:13:14:15:16:17 | +---------------> | MAC: 20:21:22:23:24:25:26:27 |
|         PAN: 0x0000          |                   |         PAN: 0x0000          |
|                              |                   |                              |
+------------------------------+                   +------------------------------+
```

So far, I've narrowed the issue down to somewhere in the RF233 state machine, but I haven't managed to get to it yet because inserting `debug!` statements that close changes the timing and the tests pass. If anyone has any thoughts, let me know!

**Comment by ppannuto** [comment]
As a testing aid, you may try using `debug_gpio!` instead of printing debug. Attach a saleae for timestamping the long-running trace and to let you monitor a bunch of gpios.

**Comment by jlwatson** [comment]
Forgot about that -- thanks!
