### ISSUE TITLE
DMA interrupt timing issue

### ISSUE THREAD

**Issue by hchiang** [tock/tock#951]
If you try to send a lot of data over SPI, it only succeeds when the clock is divided by at least ~140.

The SPI capsule uses buffers of size 64, so if you try to send 200 bytes of data, it gets divided into four calls to `read_write_bytes`. The problem is that if the clock used is not that much faster than the SPI's baud rate (in `set_baud_rate` the clock divider value SCBR is set to less than ~100), only the first (sometimes also second) call to `read_write_bytes` succeeds. 

It looks like it might be a DMA issue, since SPI's `xfer_done` function expects two interrupts for `read_write_bytes`, one for SPI_TX followed shortly by another for SPI_RX. Instead, when the clock divisor value is small, only the SPI_TX interrupt is received and the SPI hangs waiting for the SPI_RX interrupt. What's odd about this is that it doesn't always fail after the first `read_write_bytes`; in some cases the SPI_RX interrupt is received for the first `read_write_bytes` but is not received for the second call to `read_write_bytes`.

It looks like an interrupt timing issue, but I have not been able to track down the cause and help would be greatly appreciated.

If the SPI sets SCBR to be about 140 or greater, you get the following:
![screenshot from 2018-05-23 15-44-04](https://user-images.githubusercontent.com/6364543/40455104-4738caa4-5ea0-11e8-882d-9c7ca27191bc.png)

If the SPI sets SCBR to be less than 100, you get one of the following:
![screenshot from 2018-05-23 15-44-40](https://user-images.githubusercontent.com/6364543/40455275-1606a3b0-5ea1-11e8-8100-14e2a9eea0c4.png)
![screenshot from 2018-05-23 15-44-23](https://user-images.githubusercontent.com/6364543/40455268-0f2e85a8-5ea1-11e8-99bf-56b440d365de.png)

**Comment by bradjc** [comment]
Is it reasonable to just enforce that the clock has to be fast enough, given the SPI clock speed?

I've spent way too much time in the black hole that is the SAM4L, and by all accounts the SAM4L does some weird stuff with clocks.

**Comment by hchiang** [comment]
It kind of makes it hard for the SPI to have a baud rate above ~300Kbit/s and it's possible it will become an issue with other peripherals if they try using some of the slower clocks like the RC1M.

**Comment by phil-levis** [comment]
Are SPI_RX and SPI_TX GPIO lines you are toggling in the interrupts? How are you generating those signals?

**Comment by hchiang** [comment]
They're gpio_debug outputs.

**Comment by phil-levis** [comment]
When exactly do they occur? I mean, the delay between the SPI completion and the TX in the lower figure is huge...

**Comment by hchiang** [comment]
That figure was generated using the RC1M as the system clock whereas the above graphs were generated using DFLL or RCFAST.

**Comment by phil-levis** [comment]
In what exact piece of code are the pins toggled?

**Comment by hchiang** [comment]
At the beginning of the xfer_done function of spi.rs, though the output is almost exactly the same if you instead toggle them in the handle_interrupt function of dma.rs.

**Comment by hchiang** [comment]
It seems to be an issue with the DMA and not with SPI since I observed a similar issue for the ADC. When running the userland/examples/tests/adc application with the main clock set to RC1M, the interrupt is not triggered for buffered ADC samples at >= 5000 Hz. The application works as expected for other clocks including RCFAST at 4MHz sampling at a rate of 175 KHz.

**Comment by alevy** [comment]
This seems _most likely_ to be a logic error in the DMA driver that happens not to manifest with slower clocks.
