### ISSUE TITLE
Create a crate for kernel/common/*Cell?

### ISSUE THREAD

**Issue by dancrossnyc** [tock/tock#986]
It would be really neat if the *Cell modules (TakeCell, MapCell, VolatileCell, etc) were available as a crate!

**Comment by bradjc** [comment]
If this is useful it seems like a good idea to me.

I would like to see a new folder for these crates (including tock_regs) because I don't think that tools is great fit if there are going to be multiple of these split off.

**Comment by alevy** [comment]
How about `extern`? `utils`?

**Comment by dancrossnyc** [comment]
`utils` would be good. I could definitely find a use for it!

**Comment by brghena** [comment]
I'm worried that `utils` is too vague, especially in the root next to a directory called `tools`. What about `libraries`? Or `crates`?

**Comment by bradjc** [comment]
PR: https://github.com/tock/tock/pull/1014

**Comment by bradjc** [comment]
Ok done!

**Comment by dancrossnyc** [comment]
This is wonderful! Thank you!
